# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Save the Forest
description:      'This is where you put your project short description'

#Github Pages site and baseurl, submodule name
url:                https://hannahwadhwa.github.io
baseurl:            /save-the-forest
submodule:          /new_template          

#Local site
url:                #http://localhost:4000

# Where things are - include submodule in path
source:       .
destination:  ./_site
plugins_dir:  ./new_template/_plugins
layouts_dir:  ./new_template/_layouts
data_dir:     ./new_template/_data
includes_dir: ./new_template/_includes

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"

#Google Analytics tracking id
analytics:        UA-82889450-1

author:
  name:           'You Name'
  twitter:        https://twitter.com/yourtwitterhandle

gems:             [jekyll-paginate, jekyll-gist]
